
services:
  db:
    container_name: db
    image: postgres:15.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=numerology
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=100
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.21
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@normail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - PGHOST=localhost
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - ./numerology-server:/docker-backend
    ports:
      - "3000:3000"